### ISSUE TITLE
Warehouse creation fails with "invalid property QUERY_ACCELERATION_MAX_SCALE_FACTOR" but none passed into resource

### ISSUE THREAD

**Issue by markfickett** [pulumi/pulumi-snowflake#282] opened 2023-07-06 15:09 UTC
### What happened?

I'm trying to create a warehouse. I didn't specify query acceleration, but get an error about it.

### Expected Behavior

I would expect creation to succeed.

### Steps to reproduce

With this warehouse definition:
```py
    wh = snowflake.Warehouse(
        "MY_WH",
        name="MY_WH",
        comment="Execute queries for all environments.",
        warehouse_size="XSMALL",
    )
```

I get this error:
```
invalid property 'QUERY_ACCELERATION_MAX_SCALE_FACTOR'; feature 'Query Acceleration Service' not enabled
```

The documented defaults for query acceleration are None, so I think omitting them shouldn't result in this error / should work even without this feature.

### Output of `pulumi about`

```
$ pulumi about
CLI
Version      3.65.1
Go Version   go1.20.3
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.13.0
eks         1.0.2
honeycomb   0.0.15
kubernetes  3.23.1
python      unknown  # actually 3.10.11, not sure why it's unknown
snowflake   0.28.0

Host
OS       ubuntu
Version  20.04
Arch     x86_64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by AaronFriel** [comment] 2023-07-07 01:12
@markfickett Sorry you ran into this! It looks like the upstream provider had a regression, this was fixed earlier this year (#172) and reintroduced. We're tracking the next release of the upstream provider which should contain a fix for this.

**Comment by mjeffryes** [comment] 2023-08-28 23:50
Closing due to inactivity

**Closed by mjeffryes** 2023-08-28 23:50 UTC
Labels: kind/bug, awaiting-feedback

**Comment by AaronFriel** [comment] 2023-08-29 00:14
@mjeffryes it looks like we can close this as fixed by the upstream?
