### ISSUE TITLE
Can not create pipes due to error - SQL compilation error: Table 'TABLE_NAME' does not exist (but the table is pre existing)

### ISSUE THREAD

**Issue by fadiabassi** [pulumi/pulumi-snowflake#129] opened 2022-07-07 08:33 UTC
### What happened?

When i try to create a pipe using snowflake pulumi provider it fails with the error that the table does not exist. But the table is already pre existing. I doubted at first that the copy into statement is not correct but when i copy paste it into the UI it creates the pipe correctly. the stage also is existing  and is accessible.

I tried many different manipulation like fully qualifying the name of the table but without a chance.

Can you please assist on this issue ? 

### Steps to reproduce

1- Create a database, schema and a table 
2- Create a stage 
3- Create a pipe with the script 
`        pipe = snowflake.Pipe(resource_name=pipe_name,
                              auto_ingest=True,
                              name=pipe_name,
                              copy_statement=query,
                              database=database_name,
                              schema=schema_name,
                              opts=pulumi.ResourceOptions(depends_on=[stage]))`

### Expected Behavior

A snowpipe should be created. 

### Actual Behavior

an error 

`    error: 1 error occurred:
        * error creating pipe PIPE_TENANT: 001757 (42601): SQL compilation error:
    Table 'IND' does not exist`

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by damianh** [comment] 2022-07-18 14:40
@fadiabassi You need to connect with the snowflake-labs folks on https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1095 . There isn't anything the Pulumi team can do here. @jkodroff You may wish to close this issue (or keep it open for tracking pending upstream fix). Cheers.

**Comment by stack72** [comment] 2022-07-20 04:15
Going to close this out as a duplicate of an upstream issue

**Closed** 2022-07-20 04:16 UTC
Labels: kind/bug, resolution/duplicate, awaiting-upstream
