### ISSUE TITLE
Grants on snowflake objects are non-idempotent

### ISSUE THREAD

**Issue by mkoehrsen** [pulumi/pulumi-snowflake#55] opened 2022-01-18 22:07 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I have a project that instantiates multiple snowflake objects of different types (warehouses, databases, schemas), and multiple roles, and then tries to grant different privileges on the snowflake objects to the roles. If I grant the same privilege on the same object (e.g. `USAGE` on a single database) to different roles using different `DatabaseGrant` objects then it works fine the first time I instantiate the stack. However, if I do `pulumi up` a second time with the same code it detects and tries to apply spurious changes.

The underlying problem appears to be that an internal identifier is created using the target object name and the privilege name, but this isn't guaranteed unique.

### Steps to reproduce

1. Create a new Python project with `pulumi new`.
2. Copy the attached `__main__py.txt` file to the project and rename it as `__main__.py`.
3. Run `pulumi up` with appropriate credentials and apply the changes specified by the project.
4. Run `pulumi up` a second time.

Expected: Pulumi detects no changes to apply, and exits.
Actual: Pulumi detects changes to the `roles` property of one of the database grants, and gives the option of performing the update.

[__main__py.txt](https://github.com/pulumi/pulumi-snowflake/files/7892621/__main__py.txt)

**Comment by raphael-riel** [comment] 2023-01-17 16:45
This was caused by a Terraform limitation that now fixed: https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/824

**Comment by AaronFriel** [comment] 2023-02-06 17:31
We've merged in the upstream fix with [v0.15.0](https://github.com/pulumi/pulumi-snowflake/releases/tag/v0.15.0) and newer.

**Closed by AaronFriel** 2023-02-06 17:31 UTC
Labels: kind/bug, resolution/fixed
