### ISSUE TITLE
`schema_name` field is still required when `on_future` is set to `True` for FunctionGrant, ProcedureGrant, and FileFormatGrant

### ISSUE THREAD

**Issue by novikovaTanya** [pulumi/pulumi-snowflake#96] opened 2022-03-14 18:50 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

From the docs for the [FileFormatGrant](https://www.pulumi.com/registry/packages/snowflake/api-docs/fileformatgrant/):
![image](https://user-images.githubusercontent.com/8155851/158234990-b34fb6e3-5190-4af4-a431-b2bd7843f8a2.png)
the `schema_name` is marked as a required field but at the same time the description for the `on_future` field mentions that if it is set to `True` and no `schema_name` is provided the privilege on all future file formats in the given database will be granted.
I am unable to create a future grant on file formats because pulumi throws an error requiring the `schema_name` field.
I see the same issue when I try to grant `USAGE` on future functions or procedures (FunctionGrant, ProcedureGrant).

pulumi>=3.0.0,<4.0.0
pulumi-snowflake==0.4.2
python3.8

### Steps to reproduce

1. Create FileFormatGrant with `on_future=True` and no `schema_name` field (or explicitly set `schema_name` to `None`):
```python
pulumi.pulumi_snowflake.FileFormatGrant(
    resource_name="future_file_formats_usage_grant",
    opts=opts,
    database_name="TEST_DB",
    on_future=True,
    privilege="USAGE",
    roles=["TEST_ROLE"],
    with_grant_option=False
)
```
2. Run `pulumi up`

Expected: 
The plan succeeds and once confirmed the privilege `USAGE` on future file format/procedure/function is granted to the role.
Actual: 
An error is thrown:
```sh
      ...
      File "/home/tetiana/.local/lib/python3.8/site-packages/pulumi_snowflake/file_format_grant.py", line 346, in __init__
        __self__._internal_init(resource_name, *args, **kwargs)
      File "/home/tetiana/.local/lib/python3.8/site-packages/pulumi_snowflake/file_format_grant.py", line 378, in _internal_init
        raise TypeError("Missing required property 'schema_name'")
    TypeError: Missing required property 'schema_name'
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

Note: adding an empty string for the schema_name, like `schema_name="",`, seem to be fixing the issue, and the future privileges for functions/procedures/fileformats are granted.

**Comment by viveklak** [comment] 2022-03-21 19:47
Looks like the TF resource schema marks `schema_name` as required: https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/main/pkg/resources/file_format_grant.go#L24 which is being interpreted by terraform-bridge to mark this as a required field in Pulumi. @jkodroff do we need to override the resource schema?

**Comment by novikovaTanya** [comment] 2022-03-21 20:30
I missed those before, but there are already bugs related to this issue for future grants on procedures/functions/file_formats/and others? filed on the TF provider's side:
https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/658
https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/682

**Comment by viveklak** [comment] 2022-03-21 21:53
@novikovaTanya thanks for checking. Yes that is the issue. Once the terraform schema supports this, the Pulumi provider will do so as well.

**Comment by stack72** [comment] 2022-07-20 04:17
I am going to close this out as a duplicate of upstream - this will automatically flow into this provider when it;'s fixed upstream

**Closed by stack72** 2022-07-20 04:17 UTC
Labels: kind/bug, resolution/duplicate, awaiting-upstream
